### ISSUE TITLE
Found a small error in  sfw_planner.cpp

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/social_force_window_planner#10]
Hello.
Thanks again for your help.
I found a very small mistake in the program.
In sfw_planner.cpp, on lines 144 and 145 :

std::printf("%.2f, ", (i * angvel_step));
std::printf("%.2f, ", (i * (-angvel_step)));

but I think angvel is a mistake for linvel, isn't it?

**Comment by noeperez** [comment]
Yes, angvel_step is the correct one. 
I have fix it.

**Comment by hatta-yuuto** [comment]
Thank you for your confirmation.
