### ISSUE TITLE
Robot rotates around the global path only in real environment

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/social_force_window_planner#12]
Hello.
I'm planning to use this planner in a real environment.
It works well in simulation, but in real environment, the robot often rotates around the global path. The parameters are all the same, but for some reason the robot moves differently in the real environment than in the simulation. The rotation around the global path is a little better when the angle_weight is increased, but the motion is still different from the simulation. Is this planner or its dependent packages not well suited for real-world use?
Or is it my settings that are wrong?

**Comment by noeperez** [comment]
Hello, 
there are always differences between a simulated and a real environment. First, you must adjust some parameters according to your robot (velocities and accelerations are crucial) and maybe the weights of the cost functions as you commented.

**Comment by hatta-yuuto** [comment]
Thank you.
