### ISSUE TITLE
Is this package compatible with ROS kinetic?

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/social_force_window_planner#2]
Hi.
I'm using ROS kinetic, is this package compatible with kinetic?
I'm having trouble catkin_make.
If it doesn't support kinetic, what do I need to change to be able to use kinetic?

**Comment by noeperez** [comment]
Hi,

the package was developed under ROS Noetic. 
The problem to be used in another ROS distro, like Kinetic, is that the nav_core::BaseLocalPlanner plugin requires different parameters in its constructor. 
For Kinetic, a tf::TransformListener is required whereas a tf2_ros::Buffer is employed in the Noetic plugin. 
So, if you want to use the package in Kinetic, you would need to recode the class sfw_planner_ros (which inherits from nav_core::BaseLocalPlanner).

**Comment by hatta-yuuto** [comment]
Thank you very much.
