### ISSUE TITLE
Use gazebo_sfm_plugin and pedlab

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/social_force_window_planner#3]
Hi. Thank you very much for your help.
I am currently using social_force_window_planner to control a wheelchair on ROS. It is working fine.
Is it possible to use gazebo_sfm_plugin and pedlab to represent a pedestrian in the same environment?
I am trying to simulate a situation where a wheelchair avoids pedestirans.

**Comment by noeperez** [comment]
Hi again,

yes, you can use gazebo_sfm_plugin to simulate pedestrians in you Gazebo environment.

Pedlab is not necessary, and besides, it's not functional at the moment. It depends on custom people messages that are not available. We will change them for the generic ros people_msgs at some point.

**Comment by hatta-yuuto** [comment]
Thank you again.
