### ISSUE TITLE
How to use this package in a simulation of a wheelchair avoiding a pedestrian

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/social_force_window_planner#4]
Nice to meet you.
I'm new to ROS.
I'm trying to create a simulation where a wheelchair automatically avoids pedestrians. Currently, I am using DWA Planner ROS to control the wheelchair, but I have changed to SFW Planner ROS and confirmed that the wheelchair can reach the destination in a space without pedestrians. In the future, I would like to simulate avoidance by adding pedestrians to the environment, but is it possible to avoid pedestrians by predicting their behavior using only SFW Planner ROS and its dependent packages? 
(In this case, is it correct that the wheelchair is subject to repulsion from the pedestrian, attraction from the goal, and repulsion from the obstacle?) Also, what settings are required in each dependent package when running such a simulation?

**Comment by noeperez** [comment]
Dear So-chibun,

The SFW planner can receive the pedestrians information through the topic "people_topic" and/or "dyn_obs_topic", as indicated in the documentation. So, you need another package able to sense people and to publish the proper messages.
You can simulate people in Gazebo simulator by using the "gazebo_sfm_plugin", and the package "dynamic_obstacle_detector" can be used to detect dynamic obstacles (moving people in this case) among other available packages.  

Beyond that, I must say that this package is intended for people with knowledge of ROS and its navigation stack. Moreover, Github issues is a tool for tracking the development of the code, indicating possible bugs and next steps in the development. So, this is not the most appropriate place for introductory explanations and guides. The required information is included in the readme page.

**Comment by So-chibun** [comment]
Thank you.
