### ISSUE TITLE
costmap_cost is always 0

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/social_force_window_planner#5]
Hello.
I have made some changes to my program to be able to display the cost values during the simulation.
However, only cost_map_cost is always showing 0. Where does the program get the information for the cost map?

**Comment by noeperez** [comment]
Hello,

the costmap_cost is taken from the ROS local costmap. I have checked my system and the value is taken correctly. Are you sure you are launching the ros move_base properly configured?

**Comment by So-chibun** [comment]
Thank you.
I will check move_base.
