### ISSUE TITLE
Detection accuracy of dynamic obstacles

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/social_force_window_planner#6]
Thank you very much for your help. Is it correct that my_agents.size() in line 584 of sfw_planner.cpp represents the number of detected dynamic obstacles + 1 (robot itself)? When I modified the program to display this value during the simulation, it sometimes displayed various values such as 4 or 5 even though there was only one robot and one pedestrian. In addition, visualization with rviz showed some moving points other than the actual pedestrians. Is it collect to assume that this is a problem with the accuracy of the dynamic_obstacle_detector package or the performance of the robot's sensor? I am currently using 2d lidar for my simulation.
(My previous question about costmap_cost was resolved. Sorry for the inconvenience.)

**Comment by noeperez** [comment]
Yes, it is correct; the agents size takes into account the robot.

Regarding the dynamic obstacles detector, as it is said in the documentation, it is a very simple detector that does not perform a very good detection. Sometimes it senses the two legs as independent obstacles, and the moving occlusions in the background walls provoked by the moving people are detected as dynamic obstacles too. Anyway, these false detections in the background should not affect the planner too much. 

We are working in much better detectors, but that package is used to test the social planners for the moment.

**Comment by So-chibun** [comment]
I apologize for the delay in thanking you.
 Thank you very much for your answer.
