### ISSUE TITLE
Adjust Parameters

### ISSUE THREAD

**Issue by So-chibun** [robotics-upo/social_force_window_planner#7]
Thank you very much for your help.
I am running a simulation using SFW, but no matter which of the following weights I adjust: social_weight, costmap_weight, angle_weight, distance_weight, velocity_weight, it still crashes into an obstacle.
What other parameters do I need to adjust?

**Comment by noeperez** [comment]
If the ros local costmap is properly configured, you should only increase the costmap weight.

**Comment by So-chibun** [comment]
Thank you very much.
So if local　costmap is set perfectly, the other parameters can be left as default?

**Comment by noeperez** [comment]
You must adjust the local costmap for the behaviour that you want by increasing and decreasing the length of the costmap around obstacles and their costs. Then, you adjust the costmap weight of the SFW planner.
The rest of parameters can be left as default unless you want to change the robot behaviour.

And I must repeat that this is not the place for a tutorial. The code is intended to be used by people with knowledge or ROS and its navigation stack, so they can understand and adjust the planner with the code and the provided information. Only code problems and bugs should be commented here.
